### 

@baseUrl = {{host}}/api/v1
@host = http://localhost:3000

# Register

POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "newuser3@agenciapro.com",
  "name": "user2",
  "password": "password123",
  "role": "admin"
}


### 

# Login

POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "newuser3@agenciapro.com",
  "password": "password123"
}


### 
