
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: farmacia-postgres
    environment:
      POSTGRES_DB: farmacia
      POSTGRES_USER: farmacia
      POSTGRES_PASSWORD: farmacia
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U farmacia"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: farmacia-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
